import type { Story } from './types'

export const MOCK_STORIES: Story[] = [
  { id: 'm01', lat: 48.8, lng: 2.3,   countryCode: 'FR', headline: 'France holds emergency security summit amid regional tensions', summary: 'French president convenes national security council to discuss border security and regional stability following recent incidents.', url: 'https://www.bbc.com/news', source: 'BBC News', publishedAt: new Date().toISOString(), ago: '1h', category: 'politics', importance: 4, minZoom: 2 },
  { id: 'm02', lat: 51.5, lng: -0.1,  countryCode: 'GB', headline: 'UK economy shows signs of recovery as inflation falls', summary: 'Latest ONS figures show inflation dropping to 3.2%, boosting hopes of interest rate cuts later this year.', url: 'https://www.bbc.com/news', source: 'BBC World News', publishedAt: new Date().toISOString(), ago: '2h', category: 'economy', importance: 3, minZoom: 4 },
  { id: 'm03', lat: 49.8, lng: 36.2,  countryCode: 'UA', headline: 'Ukraine reports renewed shelling in eastern regions', summary: 'Ukrainian military says Russian forces launched overnight strikes on Kharkiv and surrounding villages.', url: 'https://www.aljazeera.com', source: 'Al Jazeera', publishedAt: new Date().toISOString(), ago: '3h', category: 'conflict', importance: 5, minZoom: 2 },
  { id: 'm04', lat: 31.8, lng: 35.2,  countryCode: 'IL', headline: 'Gaza ceasefire talks resume in Cairo', summary: 'Mediators from Egypt and Qatar working to broker a deal as humanitarian situation deteriorates.', url: 'https://www.aljazeera.com', source: 'Al Jazeera', publishedAt: new Date().toISOString(), ago: '4h', category: 'diplomacy', importance: 5, minZoom: 2 },
  { id: 'm05', lat: 35.7, lng: 51.4,  countryCode: 'IR', headline: 'Iran nuclear talks stall over inspection access', summary: 'IAEA negotiations break down after Tehran rejects proposed monitoring conditions.', url: 'https://www.bbc.com/news', source: 'BBC News', publishedAt: new Date().toISOString(), ago: '5h', category: 'diplomacy', importance: 4, minZoom: 2 },
  { id: 'm06', lat: 28.6, lng: 77.2,  countryCode: 'IN', headline: 'India-Pakistan border tensions escalate after exchange of fire', summary: 'Both nations report casualties along the Line of Control in Kashmir, with diplomatic talks suspended.', url: 'https://www.bbc.com/news', source: 'BBC News', publishedAt: new Date().toISOString(), ago: '6h', category: 'conflict', importance: 5, minZoom: 2 },
  { id: 'm07', lat: 39.9, lng: 116.4, countryCode: 'CN', headline: 'China GDP growth beats expectations at 5.3%', summary: 'National Bureau of Statistics reports stronger-than-expected first quarter growth driven by exports.', url: 'https://www.bbc.com/news', source: 'BBC News', publishedAt: new Date().toISOString(), ago: '7h', category: 'economy', importance: 3, minZoom: 4 },
  { id: 'm08', lat: -15.8, lng: -47.9, countryCode: 'BR', headline: 'Amazon deforestation rate drops 50% under new policies', summary: 'Brazil\'s space agency INPE reports significant reduction in Amazon clearing as enforcement increases.', url: 'https://www.bbc.com/news', source: 'BBC News', publishedAt: new Date().toISOString(), ago: '8h', category: 'climate', importance: 4, minZoom: 2 },
  { id: 'm09', lat: 55.7, lng: 37.6,  countryCode: 'RU', headline: 'Russia announces new military mobilisation drive', summary: 'Defence ministry calls for additional recruits as fighting continues across multiple fronts.', url: 'https://www.aljazeera.com', source: 'Al Jazeera', publishedAt: new Date().toISOString(), ago: '9h', category: 'conflict', importance: 4, minZoom: 2 },
  { id: 'm10', lat: 38.9, lng: -77.0, countryCode: 'US', headline: 'US Congress debates major foreign aid package', summary: 'Senate votes on $95bn aid bill covering Ukraine, Israel and Taiwan amid fierce political debate.', url: 'https://www.bbc.com/news', source: 'BBC News', publishedAt: new Date().toISOString(), ago: '10h', category: 'politics', importance: 4, minZoom: 2 },
  { id: 'm11', lat: -26.2, lng: 28.0, countryCode: 'ZA', headline: 'South Africa elections: ANC faces tightest race in 30 years', summary: 'Polls suggest the ruling party may lose its outright majority for the first time since 1994.', url: 'https://www.bbc.com/news', source: 'BBC News', publishedAt: new Date().toISOString(), ago: '11h', category: 'politics', importance: 3, minZoom: 4 },
  { id: 'm12', lat: 6.5,  lng: 3.4,   countryCode: 'NG', headline: 'Nigeria flood disaster displaces 200,000 in river states', summary: 'Heavy seasonal rains cause worst flooding in a decade, with emergency services overwhelmed.', url: 'https://www.aljazeera.com', source: 'Al Jazeera', publishedAt: new Date().toISOString(), ago: '12h', category: 'disaster', importance: 4, minZoom: 2 },
  { id: 'm13', lat: 35.7, lng: 139.7, countryCode: 'JP', headline: 'Japan raises interest rates for first time since 2007', summary: 'Bank of Japan ends negative interest rate policy, signalling shift after decades of deflation.', url: 'https://www.bbc.com/news', source: 'BBC News', publishedAt: new Date().toISOString(), ago: '13h', category: 'economy', importance: 3, minZoom: 4 },
  { id: 'm14', lat: 30.0, lng: 31.2,  countryCode: 'EG', headline: 'Egypt mediates talks to ease Red Sea shipping crisis', summary: 'Cairo hosts emergency summit as Houthi attacks on commercial vessels continue to disrupt global trade.', url: 'https://www.aljazeera.com', source: 'Al Jazeera', publishedAt: new Date().toISOString(), ago: '14h', category: 'diplomacy', importance: 3, minZoom: 4 },
  { id: 'm15', lat: 52.5, lng: 13.4,  countryCode: 'DE', headline: 'Germany pledges €100bn defence spending boost', summary: 'Berlin announces largest military investment since World War II amid rising European security concerns.', url: 'https://www.bbc.com/news', source: 'BBC News', publishedAt: new Date().toISOString(), ago: '15h', category: 'politics', importance: 3, minZoom: 4 },
  { id: 'm16', lat: 13.5, lng: 2.1,   countryCode: 'NE', headline: 'Niger coup government expels French troops', summary: 'Junta demands French military forces leave within 30 days as relations deteriorate further.', url: 'https://www.aljazeera.com', source: 'Al Jazeera', publishedAt: new Date().toISOString(), ago: '16h', category: 'conflict', importance: 3, minZoom: 4 },
  { id: 'm17', lat: -33.9, lng: 151.2, countryCode: 'AU', headline: 'Australia records hottest autumn on record', summary: 'Bureau of Meteorology confirms unprecedented autumn temperatures linked to climate change.', url: 'https://www.bbc.com/news', source: 'BBC News', publishedAt: new Date().toISOString(), ago: '17h', category: 'climate', importance: 2, minZoom: 6 },
  { id: 'm18', lat: 23.1, lng: 113.3, countryCode: 'CN', headline: 'Taiwan Strait: Chinese navy holds largest exercise in years', summary: 'PLA Navy conducts live-fire drills near Taiwan amid heightened cross-strait tensions.', url: 'https://www.bbc.com/news', source: 'BBC News', publishedAt: new Date().toISOString(), ago: '18h', category: 'conflict', importance: 4, minZoom: 2 },
  { id: 'm19', lat: 19.4, lng: -99.1, countryCode: 'MX', headline: 'Mexico elects first female president in historic vote', summary: 'Claudia Sheinbaum wins by a landslide, becoming Mexico\'s first woman to hold the presidency.', url: 'https://www.bbc.com/news', source: 'BBC News', publishedAt: new Date().toISOString(), ago: '19h', category: 'politics', importance: 4, minZoom: 2 },
  { id: 'm20', lat: 15.6, lng: 32.5,  countryCode: 'SD', headline: 'Sudan civil war: famine conditions spreading', summary: 'UN warns of catastrophic food insecurity as fighting between army and RSF continues into second year.', url: 'https://www.aljazeera.com', source: 'Al Jazeera', publishedAt: new Date().toISOString(), ago: '20h', category: 'disaster', importance: 5, minZoom: 2 },
]
